workflows:
    version: 2
    build:
        jobs:
            - build:
                filters:
                    tags:
                        only: /^tf-.*/

                - checkout
                - run: ls -al

