version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker build -t threecheese/docker-terragrunt .
    push:
        docker:
            - image: golang:1
        steps:
            - checkout
            - run: |
                TF_VER=$(git name-rev --tags --name-only $(git rev-parse HEAD) |sed 's/^tf-//')
                docker build -t threecheese/docker-terragrunt:${TF_VER} .
                docker login -u DOCKER_LOGIN -p DOCKER_PASS
                docker push threecheese/docker-terragrunt:${TF_VER} .

workflows:
    version: 2
    release:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            - push:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^tf-.*/

