version: 2
jobs:
    build:
        docker:
            - image: golang:1
        steps:
            - checkout
            - run: ls -al
    push:
        docker:
            - image: golang:1
        steps:
            - checkout
            - run: pwd

workflows:
    version: 2
    release:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            - push:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^tf-.*/

