version: 2
jobs:
    build:
        - checkout
        - run: ls -al

workflows:
    version: 2
    release:
        jobs:
            - build_and_push:
                filters:
                    tags:
                        only: /^tf-.*/

